export enum LocationQuality {
  A = 'A',
  B = 'B',
  C = 'C',
}

export enum ProjectQuality {
  A = 'A',
  B = 'B',
  C = 'C',
}

export enum SalesStatus {
  PRIMARY = 'Primary',
  PEDING = 'Pending',
  RESALE = 'Resale',
  PRIMARY_RESALE = 'Primary Resale',
  OFF_PLANN_RESALE = 'Off Plan Resale',
  PRIMARYPLUSOFFPLANRESALE = 'Primary + Off Plan Resale',
}

export enum FacilitiesCategory {
  SHOPS = 'Shops',
  SCHOOL = 'School',
  PETROL_PUMP = 'Petrol Pump',
  HOSPITALS = 'Hospitals',
  CLINICS = 'Clinics',
  MALLS = 'Malls',
  PUBLIC_TRANSPORT = 'Public Transport',
}

export enum PlotStatus {
  Vacant = 'Vacant',
  UnderConstruction = 'Under Construction',
  Ready = 'Ready',
  Pending = 'Pending',
}

export enum FileType {
  DOCX = 'docx',
  XLSX = 'xlsx',
  CSV = 'csv',
  IMAGE = 'image',
  PDF = 'pdf',
  VIDEO = 'mp4',
}

export enum PropertyType {
  Apartment = 'Apartment',
  Shops = 'Shops',
  Offices = 'Offices',
  Hotel = 'Hotel',
  Townhouse = 'Townhouse',
  Villas = 'Villas',
  Mansions = 'Mansions',
  Showroom = 'Showroom',
  Warehouse = 'Warehouse',
  LabourCamp = 'Labour Camp',
  Hospital = 'Hospital',
  School = 'School',
  Bungalow = 'Bungalow',
}

export enum AmenitiesCategory {
  GYM = 'Gym',
  SWIMMING_POOL = 'Swimming Pool',
  SAUNA = 'Sauna',
  STEAM_ROOM = 'Steam Room',
  YOGA_ROOM = 'Yoga Room',
  AEROBICS_STUDIO = 'Aerobics Studio',
  JOGGING_TRACKS = 'Jogging / walking tracks',
  TENNIS_COURT = 'Tennis Court',
  BADMINTON_COURT = 'Badminton Court',
  BASKETBALL_COURT = 'Basketball Court',
  CRICKET_GROUND = 'Cricket Ground',
  TABLE_TENNIS = 'Table Tennis',
  BILLIARDS = 'Billiards',
  CLUBHOUSE = 'Clubhouse',
  DANCE_STUDIO = 'Dance Studio',
  MINI_GOLF = 'Mini Golf',
  PADEL_TENNIS = 'Padel Tennis',

  LANDSCAPED_GARDEN = 'Landscaped Garden',
  PARK = 'Park',
  PLAYGROUND = 'Playground',
  PICNIC_AREA = 'Picnic Area',
  BARBECUE_STATIONS = 'Barbecue / grill stations',
  PET_PARK = 'Pet Park',
  WATER_PARK = 'Water Park',
  ROOFTOP_GARDENS = 'Roof gardens, Sky Decks',
  COMMUNITY_FARMING = 'Community farming, Garden plots',

  CHILDREN_PLAY_AREA = 'Children Play Area',
  DAYCARE = 'Daycare / Nursery',
  KIDS_POOL = 'Kids Pool',
  GAME_ZONE = 'Teen lounge / Game zone',
  EDUCATION_CENTER = 'Education center / Library',

  GROCERY = 'Grocery',
  ATM_BANK = 'ATM / Bank Kios',
  RESTAURANT = 'Café / Restaurant/ Food Court',
  LAUNDRY = 'Laundry',
  BUSINESS_CENTER = 'Business Center',
  LOCKERS = 'Lockers',
  CONCIERGE = 'Concierge / Help Desk',

  COVERED_PARKING = 'Covered Parking',
  VISITOR_PARKING = 'Visitor Parking',
  EV_CHARGING = 'EV Charging Station',
  BICYCLE_RACKS = 'Bicycle racks / storage',
  SHUTTLE_SERVICE = 'Shuttle Service / Transport access',

  SECURITY_247 = '24/7 Security',
  CCTV = 'CCTV Surveillance',
  GATED_ACCESS = 'Gated Access',
  INTERCOM = 'Intercom system',
  FIRE_SAFETY = 'Fire Safety Systems',

  RAINWATER_HARVESTING = 'Rainwater Harvesting',
  SOLAR_PANELS = 'Solar Panels',
  SMART_HOME = 'Smart Home Features',

  BANQUET_HALL = 'Banquet Hall',
  MINI_CINEMA = 'Private theater / Mini cinema',
  AMPHITHEATER = 'Amphitheater',
  MUSIC_ROOM = 'Music Room / Jamming studio',
  KARAOKE_ROOM = 'Karaoke Room',
  ROOFTOP_BAR = 'Lounge / Rooftop Bar',
  HOBBY_ROOM = 'Hobby Room',
  COMMUNITY_KITCHEN = 'Community Kitchen',
  READING_LOUNGE = 'Book café or Reading Lounge',
  NURSE_STATION = 'On-call medical services / Nurse station',
  PRAYER_HALL = 'Prayer Hall',

  HANDYMAN_SERVICES = 'Handyman on-call services',
  PEST_CONTROL = 'Pest control & Fumigation Support',
  GREEN_CERTIFICATION = 'Green Building Certification',
  RECYCLING_POINTS = 'Community Recycling Points',
}

export enum unitType {
  STUDIO = 'Studio',
  OFFICE = 'Office',
  SHOP = 'Shop',
  BEDROOM = 'BedRoom',
}

export enum UnitPurpose {
  RENT = 'Rent',
  SELL = 'Sell',
  MANAGE = 'Manage',
  DEVELOP = 'Develop',
  VALUATION = 'Valuation',
  HOLD = 'Hold',
  PENDING = 'Pending',
}

export enum RoomType {
  MaidsRoom = 'Maid’s Room',
  StudyOrHomeOffice = 'Study / Home Office',
  StorageRoom = 'Storage Room',
  LaundryRoom = 'Laundry Room',
  PrayerRoom = 'Prayer Room',
  DriversRoom = 'Driver’s Room',
  CinemaRoom = 'Cinema Room',
  PetRoom = 'Pet Room',
  NurseryOrBabyRoom = 'Nursery / Baby Room',
  TeenLoungeOrKidsPlayroom = "Teen Lounge / Kids' Playroom",
} 
export enum CustomerSegment {
  Customer = 'Customer',
  Supplier = 'Supplier',
}

export enum CustomerCategory {
  Organisation = 'Organisation',
  Individual = 'Individual',
}

export enum CustomerSubCategory {
  EndUser = 'End User',
  Investor = 'Investor',
}

export enum CustomerType {
  Seller = 'Seller',
  TenantLongTerm = 'Tenant-Long Term',
  TenantShortTerm = 'Tenant-Short Term', 
  Buyer = 'Buyer',
  ProspectBuyer = 'Prospect Buyer',
  PropertyOwner = 'Property Owner',
  SubLease = 'Sub-Lease',
  Landlord = 'Landlord',
  Underwriter = 'Underwriter',
  ShortTermTrader = 'Short Term Trader',
} 
export enum CustomerSubType {
  MasterDeveloper = 'Master Developer',
  SubDeveloper = 'Sub-Developer',
  RealEstateInvestor = 'Real Estate Investor',
  RealEstateBroker = 'Real Estate Broker',
  PropertyManagement = 'Property Management',
  Banks = 'Banks',
  Auction = 'Auction',
  Contractor = 'Contractor',
  ArchitectConsultant = 'Architect-Consultant',
  REIT = 'REIT',
  PrivateInvestor = 'Private Investor',
} 

export enum customerBusinessSector {
  RealEstateInvestmentAndDevelopment = "Real Estate Investment & Development",
  AgricultureForestryAndFishing = "Agriculture, Forestry & Fishing",
  MiningAndExtraction = "Mining & Extraction",
  Manufacturing = "Manufacturing",
  ConstructionAndRealEstate = "Construction & Real Estate",
  WholesaleAndRetailTrade = "Wholesale & Retail Trade",
  TransportationAndLogistics = "Transportation & Logistics",
  InformationTechnologyAndTelecommunications = "Information Technology & Telecommunications",
  FinancialServices = "Financial Services",
  ProfessionalScientificAndTechnicalServices = "Professional, Scientific & Technical Services",
  HealthcareAndSocialAssistance = "Healthcare & Social Assistance",
  Education = "Education",
  ArtsEntertainmentAndRecreation = "Arts, Entertainment & Recreation",
  AccommodationAndFoodServices = "Accommodation & Food Services",
  PublicAdministrationAndDefense = "Public Administration & Defense",
  Utilities = "Utilities",
  PersonalAndOtherServices = "Personal & Other Services",
  EnvironmentalServicesAndRenewableEnergy = "Environmental Services & Renewable Energy",
  MediaAndPublishing = "Media & Publishing",
  ChemicalsAndPetrochemicals = "Chemicals & Petrochemicals", 
  AerospaceDefenseManufacturing = "Aerospace & Defense Manufacturing",
  Automotive = "Automotive",
  BiotechnologyLifeSciences = "Biotechnology & Life Sciences",
  EcommerceDigitalTrade = "E-commerce & Digital Trade",
  TelecommunicationsServices = "Telecommunications Services",
  LogisticsTechnologySupplyChain = "Logistics Technology & Supply Chain",
  HospitalityTourism = "Hospitality & Tourism",
  TextileApparel = "Textile & Apparel",
  Pharmaceuticals = "Pharmaceuticals",
  RenewableEnergy = "Renewable Energy",
  AdvertisingMarketing = "Advertising & Marketing",
  AerospaceAviationServices = "Aerospace & Aviation Services",
  AutomotiveServicesRepair = "Automotive Services & Repair",
  BankingFinancialInstitutions = "Banking & Financial Institutions",
  BeautyPersonalCare = "Beauty & Personal Care",
  ChemicalsManufacturing = "Chemicals Manufacturing",
  ConsumerElectronics = "Consumer Electronics",
  DataCentersCloudInfrastructure = "Data Centers & Cloud Infrastructure",
  DefenseSecurity = "Defense & Security",
  DigitalMediaContentCreation = "Digital Media & Content Creation",
  EducationTechnology = "Education Technology (EdTech)",
  EnergyEquipmentServices = "Energy Equipment & Services",
  EnvironmentalTechnologyConsulting = "Environmental Technology & Consulting",
  FilmVideoProduction = "Film & Video Production",
  FoodBeverageProcessing = "Food & Beverage Processing",
  GamblingGaming = "Gambling & Gaming",
  HealthcareEquipmentSupplies = "Healthcare Equipment & Supplies", 
  HumanResourcesRecruitment = "Human Resources & Recruitment",
  IndustrialAutomation = "Industrial Automation",
  Insurance = "Insurance",
  LegalServices = "Legal Services",
  MarineOffshoreServices = "Marine & Offshore Services",
  MediaBroadcasting = "Media & Broadcasting",
  MetalsMiningEquipment = "Metals & Mining Equipment",
  NonProfitNGOs = "Non-Profit & NGOs",
  PrintingPublishing = "Printing & Publishing",
  ProfessionalTrainingCoaching = "Professional Training & Coaching",
  PublicRelations = "Public Relations",
  SoftwareDevelopment = "Software Development",
  SportsRecreation = "Sports & Recreation",
  TourismTravelServices = "Tourism & Travel Services",
  TradeExportServices = "Trade & Export Services",
  WasteManagementRecycling = "Waste Management & Recycling",
  WaterSupplyTreatment = "Water Supply & Treatment",
  WholesaleDistribution = "Wholesale Distribution",
  WoodPaperProducts = "Wood & Paper Products",
  SecurityServices = "Security Services",
  ShippingMaritimeServices = "Shipping & Maritime Services",
  SoftwareAsAService = "Software as a Service (SaaS)",
  VentureCapitalPrivateEquity = "Venture Capital & Private Equity",
  VideoGameDevelopment = "Video Game Development",
  VirtualRealityAugmentedReality = "Virtual Reality & Augmented Reality",
  WarehouseInventoryManagement = "Warehouse & Inventory Management",
  WebDevelopmentDesign = "Web Development & Design",
  WindEnergy = "Wind Energy",
  YachtMarineEquipmentManufacturing = "Yacht & Marine Equipment Manufacturing",
  ZoologicalParksAquariums = "Zoological Parks & Aquariums", 
   ZeroWasteCircularEconomy = "Zero Waste & Circular Economy",
  ThreeDPrintingServices = "3D Printing Services",
  AcademicResearch = "Academic Research",
  AdventureTourism = "Adventure Tourism",
  AgriculturalEquipmentManufacturing = "Agricultural Equipment Manufacturing",
  AirConditioningHVAC = "Air Conditioning & HVAC",
  AnimalHealthVeterinaryServices = "Animal Health & Veterinary Services",
  ArtDealersGalleries = "Art Dealers & Galleries",
  AuctionHouses = "Auction Houses",
  AutoRepairMaintenance = "Auto Repair & Maintenance",
  AviationServices = "Aviation Services",
  BabyProductsServices = "Baby Products & Services",
  BlockchainServices = "Blockchain Services",
  BoatManufacturingServices = "Boat Manufacturing & Services",
  BookPublishing = "Book Publishing",
  BuildingMaterials = "Building Materials",
  BusinessIntelligenceAnalytics = "Business Intelligence & Analytics",
  CarDealershipsLeasing = "Car Dealerships & Leasing",
  CharityFundraising = "Charity & Fundraising",
  ChildcareServices = "Childcare Services",
  CleaningServices = "Cleaning Services",
  CoachingPersonalDevelopment = "Coaching & Personal Development",
  CommercialCleaningServices = "Commercial Cleaning Services",
  CommercialRealEstate = "Commercial Real Estate",
  ComputerHardwareManufacturing = "Computer Hardware Manufacturing",
  ConsultingServices = "Consulting Services",
  ConsumerGoodsManufacturing = "Consumer Goods Manufacturing",
  CorporateTrainingDevelopment = "Corporate Training & Development",
  CourierDeliveryServices = "Courier & Delivery Services",
  DataAnalyticsBusinessIntelligence = "Data Analytics & Business Intelligence", 
  DefenseContracting = "Defense Contracting",
  DigitalContentCreation = "Digital Content Creation",
  EcommercePlatforms = "E-commerce Platforms",
  EducationalSoftwareTools = "Educational Software & Tools",
  ElectricalContracting = "Electrical Contracting",
  ElectronicsManufacturingServices = "Electronics Manufacturing Services",
  EnergyTrading = "Energy Trading",
  EnvironmentalEngineering = "Environmental Engineering",
  EventPlanningManagement = "Event Planning & Management",
  FashionRetail = "Fashion Retail",
  FinancialTechnologyFinTech = "Financial Technology (FinTech)",
  FilmTVProduction = "Film & TV Production",
  FoodProcessingPackaging = "Food Processing & Packaging",
  FreightShippingServices = "Freight & Shipping Services",
  FurnitureManufacturing = "Furniture Manufacturing",
  GamingIndustry = "Gaming Industry",
  GeneralMerchandiseRetail = "General Merchandise Retail",
  GraphicDesignServices = "Graphic Design Services",
  HealthWellnessServices = "Health & Wellness Services",
  HigherEducation = "Higher Education",
  HospitalityEventServices = "Hospitality & Event Services",
  HouseholdAppliancesManufacturing = "Household Appliances Manufacturing",
  HVACServices = "HVAC Services",
  ImportExportServices = "Import & Export Services",
  IndustrialEquipmentManufacturing = "Industrial Equipment Manufacturing",
  InformationServices = "Information Services",
  InsuranceBrokerage = "Insurance Brokerage",
  InteriorDesign = "Interior Design",
  InvestmentServices = "Investment Services", 
  ITHardwareNetworking = "IT Hardware & Networking",
  JewelryLuxuryGoods = "Jewelry & Luxury Goods",
  JournalismNewsMedia = "Journalism & News Media",
}
 

export enum CustomerNationality {
  Afghanistan = "Afghanistan",
  Albania = "Albania",
  Algeria = "Algeria",
  Andorra = "Andorra",
  Angola = "Angola",
  AntiguaAndBarbuda = "Antigua and Barbuda",
  Argentina = "Argentina",
  Armenia = "Armenia",
  Australia = "Australia",
  Austria = "Austria",
  Azerbaijan = "Azerbaijan",
  Bahamas = "Bahamas",
  Bahrain = "Bahrain",
  Bangladesh = "Bangladesh",
  Barbados = "Barbados",
  Belarus = "Belarus",
  Belgium = "Belgium",
  Belize = "Belize",
  Benin = "Benin",
  Bhutan = "Bhutan",
  Bolivia = "Bolivia",
  BosniaAndHerzegovina = "Bosnia and Herzegovina",
  Botswana = "Botswana",
  Brazil = "Brazil",
  Brunei = "Brunei",
  Bulgaria = "Bulgaria",
  BurkinaFaso = "Burkina Faso", 
  Burundi = "Burundi",
  CaboVerde = "Cabo Verde",
  Cambodia = "Cambodia",
  Cameroon = "Cameroon",
  Canada = "Canada",
  CentralAfricanRepublic = "Central African Republic",
  Chad = "Chad",
  Chile = "Chile",
  China = "China",
  Colombia = "Colombia",
  Comoros = "Comoros",
  CongoBrazzaville = "Congo (Congo-Brazzaville)",
  CostaRica = "Costa Rica",
  Croatia = "Croatia",
  Cuba = "Cuba",
  Cyprus = "Cyprus",
  Czechia = "Czechia (Czech Republic)",
  DRofCongo = "Democratic Republic of the Congo",
  Denmark = "Denmark",
  Djibouti = "Djibouti",
  Dominica = "Dominica",
  DominicanRepublic = "Dominican Republic",
  EastTimor = "East Timor (Timor-Leste)",
  Ecuador = "Ecuador",
  Egypt = "Egypt",
  ElSalvador = "El Salvador",
  EquatorialGuinea = "Equatorial Guinea",
  Eritrea = "Eritrea",
  Estonia = "Estonia",
  Eswatini = "Eswatini",
  Ethiopia = "Ethiopia",
  Fiji = "Fiji",
  Finland = "Finland", 
   France = "France",
  Gabon = "Gabon",
  Gambia = "Gambia",
  Georgia = "Georgia",
  Germany = "Germany",
  Ghana = "Ghana",
  Greece = "Greece",
  Grenada = "Grenada",
  Guatemala = "Guatemala",
  Guinea = "Guinea",
  GuineaBissau = "Guinea-Bissau",
  Guyana = "Guyana",
  Haiti = "Haiti",
  Honduras = "Honduras",
  Hungary = "Hungary",
  Iceland = "Iceland",
  India = "India",
  Indonesia = "Indonesia",
  Iran = "Iran",
  Iraq = "Iraq",
  Ireland = "Ireland",
  Israel = "Israel",
  Italy = "Italy",
  IvoryCoast = "Ivory Coast",
  Jamaica = "Jamaica",
  Japan = "Japan",
  Jordan = "Jordan",
  Kazakhstan = "Kazakhstan",
  Kenya = "Kenya",
  Kiribati = "Kiribati",
  KoreaNorth = "Korea, North",
  KoreaSouth = "Korea, South",
  Kosovo = "Kosovo", 
 Kuwait = "Kuwait",
  Kyrgyzstan = "Kyrgyzstan",
  Laos = "Laos",
  Latvia = "Latvia",
  Lebanon = "Lebanon",
  Lesotho = "Lesotho",
  Liberia = "Liberia",
  Libya = "Libya",
  Liechtenstein = "Liechtenstein",
  Lithuania = "Lithuania",
  Luxembourg = "Luxembourg",
  Madagascar = "Madagascar",
  Malawi = "Malawi",
  Malaysia = "Malaysia",
  Maldives = "Maldives",
  Mali = "Mali",
  MarshallIslands = "Marshall Islands",
  Mauritania = "Mauritania",
  Mauritius = "Mauritius",
  Mexico = "Mexico",
  Micronesia = "Micronesia",
  Moldova = "Moldova",
  Monaco = "Monaco",
  Mongolia = "Mongolia",
  Montenegro = "Montenegro",
  Morocco = "Morocco",
  Mozambique = "Mozambique", 
   Myanmar = "Myanmar (Burma)",
  Namibia = "Namibia",
  Nauru = "Nauru",
  Nepal = "Nepal",
  Netherlands = "Netherlands",
  NewZealand = "New Zealand",
  Nicaragua = "Nicaragua",
  Niger = "Niger",
  Nigeria = "Nigeria",
  NorthMacedonia = "North Macedonia",
  Norway = "Norway",
  Oman = "Oman",
  Pakistan = "Pakistan",
  Palau = "Palau",
  Panama = "Panama",
  PapuaNewGuinea = "Papua New Guinea",
  Paraguay = "Paraguay",
  Peru = "Peru",
  Philippines = "Philippines",
  Poland = "Poland",
  Portugal = "Portugal",
  Qatar = "Qatar",
  Romania = "Romania",
  Russia = "Russia",  
   Rwanda = "Rwanda",
  SaintKittsAndNevis = "Saint Kitts and Nevis",
  SaintLucia = "Saint Lucia",
  SaintVincentAndTheGrenadines = "Saint Vincent and the Grenadines",
  Samoa = "Samoa",
  SanMarino = "San Marino",
  SaoTomeAndPrincipe = "Sao Tome and Principe",
  SaudiArabia = "Saudi Arabia",
  Senegal = "Senegal",
  Serbia = "Serbia",
  Seychelles = "Seychelles",
  SierraLeone = "Sierra Leone",
  Singapore = "Singapore",
  Slovakia = "Slovakia",
  Slovenia = "Slovenia",
  SolomonIslands = "Solomon Islands",
  Somalia = "Somalia",
  SouthAfrica = "South Africa",
  SouthSudan = "South Sudan",
  Spain = "Spain",
  SriLanka = "Sri Lanka",
  Sudan = "Sudan",
  Suriname = "Suriname",
  Sweden = "Sweden",
   Switzerland = "Switzerland",
  Syria = "Syria",
  Taiwan = "Taiwan",
  Tajikistan = "Tajikistan",
  Tanzania = "Tanzania",
  Thailand = "Thailand",
  Togo = "Togo",
  Tonga = "Tonga",
  TrinidadAndTobago = "Trinidad and Tobago",
  Tunisia = "Tunisia",
  Turkey = "Turkey",
  Turkmenistan = "Turkmenistan",
  Tuvalu = "Tuvalu",
  Uganda = "Uganda",
  Ukraine = "Ukraine",
  UnitedArabEmirates = "United Arab Emirates",
  UnitedKingdom = "United Kingdom",
  UnitedStates = "United States",
  Uruguay = "Uruguay",
  Uzbekistan = "Uzbekistan",
  Vanuatu = "Vanuatu",
  VaticanCity = "Vatican City",
  Venezuela = "Venezuela",
  Vietnam = "Vietnam",
  Yemen = "Yemen",
  Zambia = "Zambia",
  Zimbabwe = "Zimbabwe",
}

